# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: secret-demo
type: Opaque
data:
  username: bXl1c2Vy # Base64 encoded value of 'myuser'
  password: bXlwYXNzd29yZA== # Base64 encoded value of 'mypassword'

